vim.cmd('set expandtab')
vim.cmd('set tabstop=2')
vim.cmd('set softtabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set number')
vim.keymap.set('n', '<leader>%', ':vsplit<CR>', { desc = 'split vertically' })
vim.keymap.set('n', '<leader>"', ':split<CR>', { desc = 'split vertically' })
vim.keymap.set('n', '<leader>h', ':wincmd h<CR>', { desc = 'navigate split left' })
vim.keymap.set('n', '<leader>j', ':wincmd j<CR>', { desc = 'navigate split down' })
vim.keymap.set('n', '<leader>k', ':wincmd k<CR>', { desc = 'navigate split up' })
vim.keymap.set('n', '<leader>l', ':wincmd l<CR>', { desc = 'navigate split right' })
